### ISSUE TITLE
Error code: 400

### ISSUE THREAD

**Issue by NShravanReddy** [e2b-dev/secure-computer-use#1]
Hi,

Here's my full code repo [https://github.com/NShravanReddy/secure-computer-use/tree/os-computer-use](url)

## To  reproduce the error I am getting,
1. I cloned the repo and then installed mini forge 
2. Modified the llm.py file code in 16, 17 lines  as,
```
LLAMA_32_OPENROUTER_MODEL = "gemini-2.0-flash-exp"
LLAMA_33_FIREWORKS_MODEL = "accounts/fireworks/models/llama-v3p3-70b-instruct"
```
3. and 49 to 55 lines as,
```
fireworks = OpenAI (
base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
api_key=os-getenv("FIREWORKS_API_KEY"),
)
llama_vision = OpenAI(
base_url="https://generativelanguage.googleapis.com/vlbeta/openai/", 
api_key=os-getenv ("'OPENROUTER_API_KEY"),
)
osatlas = Client (OSATLAS_HUGGINGFACE_SOURCE)
```

4. Then I [https://github.com/NShravanReddy/secure-computer-use/tree/os-computer-use?tab=readme-ov-file#get-started] followed step 2 to 4 mentioned in the official repo
5.  In the .env file I have given api keys 
```
E2B_API_KEY="my e2b api key"
OPENROUTER_API_KEY="open router api key"
FIREWORKS_API_KEY="fireworks api key"

```
I am getting the below error 
[e2b error.txt](https://github.com/user-attachments/files/18240514/e2b.error.txt)

**Comment by jamesmurdza** [comment]
Hi,

Can you please introduce the change you're trying to make? It looks like you're trying to replace one of the models with Gemini.

Please note: We're using three different models in this agent, so just changing one of them may not have the result you intend.

James

**Comment by NShravanReddy** [comment]
Hi ,

Change is to use gemini  model

**Comment by jamesmurdza** [comment]
The way you have implemented it in the code isn't correct. You would need to use the Gemini API (not Fireworks) to access the Gemini model.

In the future, we will make it easier to swap out models, but we need to have an agent that is working reasonably well first.
